-- 1. Optimización: Centralización de Entidades (Personas/Empresas)
CREATE TABLE gen_entidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(255) NOT NULL,
    identificacion VARCHAR(50), -- DNI, RUC, Pasaporte
    telefono VARCHAR(50),
    email VARCHAR(100),
    direccion VARCHAR(255),
    tipo_entidad VARCHAR(20), -- 'PERSONA', 'EMPRESA'
    activo BOOLEAN DEFAULT TRUE,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE sys_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_id BIGINT REFERENCES gen_entidad(id),
    autentik_uuid VARCHAR(100) UNIQUE,
    username VARCHAR(50) UNIQUE,
    activo BOOLEAN DEFAULT TRUE,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE hr_trabajador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_id BIGINT UNIQUE REFERENCES gen_entidad(id),
    usuario_id BIGINT UNIQUE REFERENCES sys_usuario(id),
    sucursal_id BIGINT, -- FK añadida luego
    codigo_empleado VARCHAR(50),
    puesto VARCHAR(100),
    fecha_contratacion DATE,
    activo BOOLEAN DEFAULT TRUE,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE pos_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_id BIGINT REFERENCES gen_entidad(id),
    limite_credito DECIMAL(19, 2) DEFAULT 0,
    dias_credito INT DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE inv_proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_id BIGINT REFERENCES gen_entidad(id),
    activo BOOLEAN DEFAULT TRUE,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

-- Configuración General y Sucursales
CREATE TABLE sys_configuracion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moneda_default_id BIGINT, -- FK luego
    iva_porcentaje_default DECIMAL(5, 2),
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_ultima_actualizacion TIMESTAMP
);

CREATE TABLE gen_sucursal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo VARCHAR(50),
    direccion VARCHAR(255),
    telefono VARCHAR(50),
    activo BOOLEAN DEFAULT TRUE,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

-- Inventario, Precios y Stock
CREATE TABLE inv_almacen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    nombre VARCHAR(100) NOT NULL,
    codigo VARCHAR(50),
    tipo_almacen VARCHAR(50), -- FISICO, TRANSITO, PROVEEDOR, MERMA
    es_externo BOOLEAN DEFAULT FALSE,
    permite_venta BOOLEAN DEFAULT TRUE,
    direccion VARCHAR(255),
    responsable_contacto VARCHAR(100),
    descripcion VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE inv_ubicacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    almacen_id BIGINT REFERENCES inv_almacen(id),
    codigo VARCHAR(50),
    descripcion VARCHAR(100),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE inv_categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE inv_unidad_medida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    abreviatura VARCHAR(10),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE inv_impuesto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    porcentaje DECIMAL(5, 2),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE inv_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    codigo_interno VARCHAR(50),
    categoria_id BIGINT REFERENCES inv_categoria(id),
    unidad_medida_id BIGINT REFERENCES inv_unidad_medida(id),
    impuesto_id BIGINT REFERENCES inv_impuesto(id),
    maneja_variantes BOOLEAN DEFAULT FALSE,
    maneja_caducidad BOOLEAN DEFAULT FALSE,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_actualizacion TIMESTAMP
);

CREATE TABLE inv_producto_variante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT REFERENCES inv_producto(id),
    nombre_variante VARCHAR(100),
    codigo_barras VARCHAR(100) UNIQUE,
    codigo_interno_variante VARCHAR(50),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE inv_lista_precio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100),
    descripcion VARCHAR(255),
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    prioridad INT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_inicio_vigencia TIMESTAMP,
    fecha_fin_vigencia TIMESTAMP,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE inv_precio_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lista_precio_id BIGINT REFERENCES inv_lista_precio(id),
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    precio_venta DECIMAL(19, 2),
    fecha_inicio_vigencia TIMESTAMP,
    fecha_fin_vigencia TIMESTAMP,
    motivo_cambio VARCHAR(255),
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE gen_moneda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(3) UNIQUE NOT NULL,
    nombre VARCHAR(50),
    simbolo VARCHAR(5),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE inv_costo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    moneda_id BIGINT REFERENCES gen_moneda(id),
    costo_unitario DECIMAL(19, 4),
    fecha_inicio_vigencia TIMESTAMP,
    fecha_fin_vigencia TIMESTAMP,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inv_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    proveedor_id BIGINT REFERENCES inv_proveedor(id),
    almacen_destino_id BIGINT REFERENCES inv_almacen(id),
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_compra TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP,
    
    tipo_documento VARCHAR(50),
    numero_documento VARCHAR(50),
    total_compra DECIMAL(19, 2),
    estado VARCHAR(20),
    observaciones TEXT
);

CREATE TABLE inv_compra_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT REFERENCES inv_compra(id),
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    cantidad DECIMAL(19, 4),
    costo_unitario DECIMAL(19, 4),
    subtotal DECIMAL(19, 2),
    fecha_caducidad TIMESTAMP
);

CREATE TABLE inv_compra_historial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT REFERENCES inv_compra(id),
    estado_anterior VARCHAR(20),
    estado_nuevo VARCHAR(20),
    usuario_id BIGINT REFERENCES sys_usuario(id),
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT
);

CREATE TABLE inv_lote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    codigo_lote VARCHAR(50),
    fecha_caducidad TIMESTAMP,
    observaciones TEXT
);

CREATE TABLE inv_existencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    almacen_id BIGINT REFERENCES inv_almacen(id),
    ubicacion_id BIGINT REFERENCES inv_ubicacion(id),
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    lote_id BIGINT REFERENCES inv_lote(id),
    cantidad_disponible DECIMAL(19, 4),
    fecha_ultima_actualizacion TIMESTAMP
);

CREATE TABLE inv_historial_existencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    almacen_id BIGINT REFERENCES inv_almacen(id),
    ubicacion_id BIGINT REFERENCES inv_ubicacion(id),
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    lote_id BIGINT REFERENCES inv_lote(id),
    cantidad_anterior DECIMAL(19, 4),
    cantidad_nueva DECIMAL(19, 4),
    diferencia DECIMAL(19, 4),
    tipo_movimiento VARCHAR(50), -- VENT, COMP, AJUS, TRAZ
    referencia_id BIGINT,
    fecha_historial TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_responsable_id BIGINT REFERENCES sys_usuario(id)
);

CREATE TABLE inv_movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimiento VARCHAR(50),
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    almacen_origen_id BIGINT REFERENCES inv_almacen(id),
    almacen_destino_id BIGINT REFERENCES inv_almacen(id),
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_movimiento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP,
    
    referencia_tipo VARCHAR(50),
    referencia_id BIGINT,
    observaciones TEXT
);

CREATE TABLE inv_movimiento_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimiento_id BIGINT REFERENCES inv_movimiento(id),
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    lote_id BIGINT REFERENCES inv_lote(id),
    cantidad DECIMAL(19, 4),
    ubicacion_origen_id BIGINT REFERENCES inv_ubicacion(id),
    ubicacion_destino_id BIGINT REFERENCES inv_ubicacion(id)
);

-- Promociones
CREATE TABLE inv_promocion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cupon VARCHAR(50),
    nombre VARCHAR(100),
    tipo_descuento VARCHAR(20),
    valor DECIMAL(19, 2),
    fecha_inicio_vigencia TIMESTAMP,
    fecha_fin_vigencia TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE,
    usuario_creacion_id BIGINT
);

CREATE TABLE inv_promocion_aplicacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promocion_id BIGINT REFERENCES inv_promocion(id),
    referencia_tipo VARCHAR(50),
    referencia_id BIGINT
);

-- Moneda Detalle
CREATE TABLE gen_moneda_denominacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moneda_id BIGINT REFERENCES gen_moneda(id),
    nombre VARCHAR(50),
    valor DECIMAL(19, 4),
    tipo VARCHAR(20), -- BILLETE, MONEDA
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE gen_moneda_tasa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moneda_origen_id BIGINT REFERENCES gen_moneda(id),
    moneda_destino_id BIGINT REFERENCES gen_moneda(id),
    tasa_conversion DECIMAL(19, 6),
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- POS
CREATE TABLE pos_punto_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    nombre VARCHAR(100),
    descripcion VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE pos_caja (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    punto_venta_id BIGINT REFERENCES pos_punto_venta(id),
    nombre VARCHAR(100),
    cookie_key VARCHAR(100),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE pos_caja_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_id BIGINT REFERENCES pos_caja(id),
    usuario_id BIGINT REFERENCES sys_usuario(id),
    fecha_inicio TIMESTAMP,
    fecha_fin TIMESTAMP,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE pos_turno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_id BIGINT REFERENCES pos_caja(id),
    usuario_cajero_id BIGINT REFERENCES sys_usuario(id),
    usuario_supervisor_id BIGINT REFERENCES sys_usuario(id),
    fecha_hora_apertura TIMESTAMP,
    fecha_hora_cierre TIMESTAMP,
    monto_inicial_efectivo DECIMAL(19, 2),
    monto_final_efectivo_declarado DECIMAL(19, 2),
    monto_final_efectivo_calculado DECIMAL(19, 2),
    diferencia DECIMAL(19, 2),
    estado VARCHAR(20)
);

CREATE TABLE pos_turno_arqueo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_id BIGINT REFERENCES pos_turno(id),
    moneda_denominacion_id BIGINT REFERENCES gen_moneda_denominacion(id),
    cantidad INT,
    total_valor DECIMAL(19, 2),
    tipo_arqueo VARCHAR(20)
);

CREATE TABLE pos_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    punto_venta_id BIGINT REFERENCES pos_punto_venta(id),
    turno_id BIGINT REFERENCES pos_turno(id),
    cliente_id BIGINT REFERENCES pos_cliente(id),
    usuario_vendedor_id BIGINT REFERENCES sys_usuario(id),
    tipo_documento VARCHAR(20),
    numero_documento VARCHAR(50),
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_bruto DECIMAL(19, 2),
    descuento_total DECIMAL(19, 2),
    impuestos_total DECIMAL(19, 2),
    total_neto DECIMAL(19, 2),
    estado VARCHAR(20),
    estado_pago VARCHAR(20),
    almacen_salida_id BIGINT REFERENCES inv_almacen(id),
    movimiento_id BIGINT,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP
);

CREATE TABLE pos_venta_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES pos_venta(id),
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    cantidad DECIMAL(19, 4),
    precio_unitario DECIMAL(19, 2),
    impuesto_id BIGINT REFERENCES inv_impuesto(id),
    descuento_monto DECIMAL(19, 2),
    subtotal DECIMAL(19, 2),
    impuestos_monto DECIMAL(19, 2)
);

CREATE TABLE pos_venta_promocion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES pos_venta(id),
    promocion_id BIGINT REFERENCES inv_promocion(id),
    monto_descuento DECIMAL(19, 2),
    fecha_aplicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pos_tipo_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    codigo_interno VARCHAR(20),
    requiere_referencia BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE pos_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES pos_venta(id),
    tipo_pago_id BIGINT REFERENCES pos_tipo_pago(id),
    monto_total DECIMAL(19, 2),
    monto_recibido DECIMAL(19, 2),
    monto_vuelto DECIMAL(19, 2),
    referencia_pago VARCHAR(100),
    fecha_pago TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_registro_id BIGINT REFERENCES sys_usuario(id)
);

CREATE TABLE pos_pago_efectivo_desglose (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT REFERENCES pos_pago(id),
    moneda_denominacion_id BIGINT REFERENCES gen_moneda_denominacion(id),
    cantidad INT,
    monto_total DECIMAL(19, 2),
    tipo_movimiento VARCHAR(20)
);

CREATE TABLE pos_devolucion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES pos_venta(id),
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    movimiento_id BIGINT,
    -- Auditoría
    usuario_creacion_id BIGINT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_modificacion_id BIGINT,
    fecha_modificacion TIMESTAMP,
    
    motivo_general VARCHAR(255),
    total_reembolso DECIMAL(19, 2),
    estado VARCHAR(20)
);

CREATE TABLE pos_devolucion_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_id BIGINT REFERENCES pos_devolucion(id),
    venta_detalle_id BIGINT REFERENCES pos_venta_detalle(id),
    producto_variante_id BIGINT REFERENCES inv_producto_variante(id),
    cantidad_devuelta DECIMAL(19, 4),
    precio_reembolso_unitario DECIMAL(19, 2),
    monto_reembolso_linea DECIMAL(19, 2)
);

-- Contabilidad
CREATE TABLE cont_periodo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50),
    fecha_inicio TIMESTAMP,
    fecha_fin TIMESTAMP,
    estado VARCHAR(20),
    usuario_cierre_id BIGINT REFERENCES sys_usuario(id),
    fecha_cierre TIMESTAMP
);

CREATE TABLE cont_cuenta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50),
    nombre VARCHAR(100),
    tipo VARCHAR(50),
    nivel INT,
    activa BOOLEAN DEFAULT TRUE
);

CREATE TABLE cont_asiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id BIGINT REFERENCES cont_periodo(id),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    descripcion VARCHAR(255),
    origen VARCHAR(50),
    origen_id BIGINT,
    sucursal_id BIGINT REFERENCES gen_sucursal(id),
    usuario_registro_id BIGINT REFERENCES sys_usuario(id),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cont_asiento_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asiento_id BIGINT REFERENCES cont_asiento(id),
    cuenta_id BIGINT REFERENCES cont_cuenta(id),
    descripcion_linea VARCHAR(255),
    debe DECIMAL(19, 2),
    haber DECIMAL(19, 2)
);
